"""Drop cover_image_url from audiobooks

Revision ID: a0e30917396e
Revises: f40e20a1a1c5
Create Date: 2025-05-06 12:16:32.138687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e30917396e'
down_revision: Union[str, None] = 'f40e20a1a1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiobooks', 'cover_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiobooks', sa.Column('cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
