"""updated audiobook table

Revision ID: c789b491122a
Revises: 
Create Date: 2025-04-21 07:08:57.700310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c789b491122a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiobooks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('audiobooks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audiobooks', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audiobooks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'audiobooks', 'categories', ['category_id'], ['id'])
    op.drop_column('audiobooks', 'file_url')
    op.drop_column('audiobooks', 'listens')
    op.drop_column('audiobooks', 'tags')
    op.drop_column('audiobooks', 'duration')
    op.drop_column('audiobooks', 'updated_at')
    op.drop_column('audiobooks', 'narrator')
    op.drop_column('audiobooks', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiobooks', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('narrator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('listens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audiobooks', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audiobooks', type_='foreignkey')
    op.alter_column('audiobooks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audiobooks', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audiobooks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audiobooks', 'category_id')
    # ### end Alembic commands ###
