"""Add thumbnail_url to chapters

Revision ID: f40e20a1a1c5
Revises: c789b491122a
Create Date: 2025-05-06 12:11:13.092451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40e20a1a1c5'
down_revision: Union[str, None] = 'c789b491122a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'thumbnail_url')
    # ### end Alembic commands ###
